---
version: 3.8

include:
  - zammad-docker-compose/docker-compose.yml
  - zammad-compose.override.yml
services:
  caddy:
    image: caddy:${VERSION:-2.8.4-alpine}
    restart: ${RESTART:-always}
    ports:
      - 80:80
      - 443:443
    expose:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${CADDYFILE:-Caddyfile}:/etc/caddy/Caddyfile
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  Caddyfile:
    driver: local
